blacklist: []
build_space: ../../build/basestation/launch
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Release
devel_layout: linked
devel_space: ../../devel/basestation/launch
extend_path: /home/developer/deploy_ws/devel/basestation/repo
install: false
install_space: ../../install/basestation/launch
isolate_install: false
jobs_args: []
log_space: ../../logs
make_args: []
source_space: .
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
