##################################################################################################
- basestation:
##################################################################################################
  - 'export YELLOW="\033[1;33m"'
  - 'export BLUE="\033[1;36m"'
  - 'export RESET="\033[0m"'

  ################################################################################################
  - docker:
  ################################################################################################

    ####################################################
    # setup
    ####################################################
    - hostname
    - whoami
    - pwd
    
    ####################################################
    # path setup
    - 'export DEPLOY_WS=/home/$USER/deploy_ws/'
    - 'export DEPLOY_SRC=$DEPLOY_WS/src/'
    - 'export DOCKER_CONFIG=field/robot/basestation'
    - 'export DOCKER_CONFIG_PATH=docker/env'
    
    ####################################################
    # print docker configuration information
    ####################################################
    - print:
      - echo -e "\n${BLUE} == Docker images to create == \n" ;
      - echo -e "\n${YELLOW}\tenv -> \t $DOCKER_CONFIG_PATH/osrf/ros.config \n" ;
      - echo -e "\n${YELLOW}\tenv -> \t $DOCKER_CONFIG_PATH/osrf/osrf.config \n" ;
      - echo -e "\n${YELLOW}\tenv -> \t $DOCKER_CONFIG_PATH/subt/ros.config \n" ;
      - echo -e "\n${YELLOW}\tenv -> \t $DOCKER_CONFIG_PATH/field/robot/basestation.config \n" ;
      - echo -e "\n${YELLOW} ** Remember to always transfer any changed configuration files! ** \n";
      - echo -e "\n${YELLOW}\t env -> \t $DOCKER_CONFIG \n" ;
      - echo -e "\n${YELLOW}\t env -> \t $DOCKER_CONFIG_PATH/subt/subt.config \n" ;
      - echo -e "\n${YELLOW}\t subt remote env filepath -> \t $DEPLOY_SRC/$DOCKER_CONFIG_PATH/$DOCKER_CONFIG.config \n"
      - while IFS= read line;
        do 
          echo -e ${BLUE} "\t$line";
        done < "$DEPLOY_SRC/$DOCKER_CONFIG_PATH/$DOCKER_CONFIG.config"

    ####################################################
    # objdet docker image
    ####################################################
    - gui:
      
      ####################################################
      # build docker images
      ####################################################
      - cd $DEPLOY_SRC/docker/scripts
      - image:
        - 'export BUILD_ARGS="--force" '
        - osrf:
          - echo $LANG
          - ./build.bash --env local/osrf/ros $BUILD_ARGS
          - ./build.bash --env local/osrf/osrf $BUILD_ARGS
        - subt:
          - ./build.bash --env local/subt/ros $BUILD_ARGS
          - ./build.bash --env field/basestation/gui $BUILD_ARGS

      ####################################################
      # start docker images
      ####################################################
      - start:
        - 'export START_ARGS=" " '
        - ./run.bash --env field/basestation/gui $START_ARGS

      ####################################################
      # stop docker images
      ####################################################
      - stop:
        - 'export STOP_ARGS="--stop --containers " '
        - ./clean.bash --env field/basestation/gui $STOP_ARGS
      
      - remove:
        - 'export STOP_ARGS="--remove --containers " '
        - ./clean.bash --env field/basestation/gui $STOP_ARGS
      
      ####################################################
      # delete docker images & corresponding containers
      ####################################################
      - delete:
        - 'export DELETE_ARGS="--containers" '
        - ./clean.bash --env field/basestation/gui $DELETE_ARGS
        - ./clean.bash --env local/subt/ros $DELETE_ARGS
        - ./clean.bash --env local/osrf/osrf $DELETE_ARGS
        - ./clean.bash --env local/osrf/ros $DELETE_ARGS
  
    ####################################################
    # misc.
    ####################################################
    - dangling:
      - docker rmi -f $(docker images -f "dangling=true" -q)
    
  ################################################################################################
  - gui:
  ################################################################################################
    # only docker container on basestation, no ssh
    - +docker:subt
    
    - hostname
    - whoami
    - pwd
    - 'export DEPLOY_WS=/home/$(whoami)/deploy_ws/'
    - 'export DEPLOY_SRC=$DEPLOY_WS/src'
    - cd $DEPLOY_SRC

    ####################################################
    # build workspaces
    ####################################################
    - build:
      - cd basestation/

      # build the hardware workspace
      - thirdparty:
        - cd thirdparty/catkin
        - if [ -f .catkin_tools/profiles/profiles.yaml ]; then
            rm .catkin_tools/profiles/profiles.yaml;
          fi
        - catkin build --force-cmake

      # build basestation workspace
      - basestation:
        - if [ -f .catkin_tools/profiles/profiles.yaml ]; then
            rm .catkin_tools/profiles/profiles.yaml;
          fi
        - catkin build --force-cmake

      # build launch workspace
      - launch:
        - cd $DEPLOY_SRC/launch/
        - if [ -f .catkin_tools/profiles/profiles.yaml ]; then
            rm .catkin_tools/profiles/profiles.yaml;
          fi
        - catkin profile set basestation
        - catkin build --force-cmake
        - catkin clean -b --yes

    ####################################################
    # clean workspaces
    ####################################################
    - clean:
      - launch:
        - cd $DEPLOY_SRC/launch/
        - if [ -f .catkin_tools/profiles/profiles.yaml ]; then
            rm .catkin_tools/profiles/profiles.yaml;
          fi
        - catkin profile set basestation
        - catkin clean -y
      - cd $DEPLOY_SRC/basestation/
      - basestation:
        - catkin clean -y
      - thirdparty:
        - cd thirdparty/catkin
        - catkin clean -y

    ####################################################
    # launch workspaces
    ####################################################
    - launch:
      ### == user can modify ==
      
      # launch configuration variables
      - 'export host=$(hostname)'
      - 'export MCAST_GROUP=224.0.0.251'
      - 'export robot=robots/basestation'
      - 'export USER=explorer'
      - 'export ROS_MASTER_URI=http://system76-pc:11311'
      # - 'export ROS_HOSTNAME=system76-pc'
      # - 'export DISPLAY=:0.0'
      
      ### == user can modify done. ==
      
      # create the bag folder
      - mkdir -p $DEPLOY_SRC/launch/ugv_setup/logging/base_station/bags/

      # get launch configuration data
      - export CONFIG_PATH="$DEPLOY_SRC/launch/robot_launch_scripting/config/"
      # parse config file for roslaunch params
      - get_config_data() {
          CONFIG_FILE=$CONFIG_PATH/${1}.config;
          while IFS='' read -r line || [[ -n "$line" ]]; do
            if [ ! "${line:0:1}" == "#" ]; then
              config_data="$config_data $line ";
            fi
          done < "$CONFIG_FILE";
          echo ${config_data};
        }
      - export -f get_config_data

      - start:
        # roscore
        # start the tmux session
        - tmux new -s launch_roscore -d
        # export screen settings
        - tmux send -t launch_roscore 'stty columns 204' ENTER
        - tmux send -t launch_roscore 'stty lines 55' ENTER
        # source
        - tmux send -t launch_roscore 'source $DEPLOY_WS/devel/basestation/launch/setup.bash' ENTER
        # run autonomy launch
        - tmux send -t launch_roscore 'roscore' ENTER
        # message user
        - echo "Launch deployed in tmux session launch_roscore"      
        # parse the launch configuration params
        - export config=robots/basestation/gui
        - export config_data=$(get_config_data "$config")
        # gui
        - tmux new -s launch_gui -d
        # source
        - tmux send -t launch_gui 'source $DEPLOY_WS/devel/basestation/launch/setup.bash' ENTER
        # manually set the tmux env vars...for now.
        - tmux send -t launch_gui 'unset config_data' ENTER
        - tmux send -t launch_gui 'export config=robots/basestation/gui' ENTER
        - tmux send -t launch_gui 'export config_data=$(get_config_data "$config")' ENTER
        # run autonomy launch
        - tmux send -t launch_gui 'mon launch robot_launch_scripting subt.launch robot:=$robot $config_data' ENTER
        # message user
        - echo "Launch deployed in tmux session launch_gui"
        - pwd
        - tmux new -s ros_shell -d
        # export screen settings
        - tmux send -t ros_shell 'stty columns 204' ENTER
        - tmux send -t ros_shell 'stty lines 55' ENTER
        - tmux send -t ros_shell 'source $DEPLOY_WS/devel/basestation/launch/setup.bash' ENTER
        # start record hardware
        - tmux new -s launch_rosbag -d
        # source
        - tmux send -t launch_rosbag 'source $DEPLOY_WS/devel/basestation/launch/setup.bash' ENTER
        # manually set the tmux env vars...for now.
        - tmux send -t launch_rosbag 'unset config_data' ENTER
        - tmux send -t launch_rosbag 'export config=robots/basestation/rosbag' ENTER
        - tmux send -t launch_rosbag 'export config_data=$(get_config_data "$config")' ENTER
        # launch rosbag
        - tmux send -t launch_rosbag 'eval $config_data' ENTER
        # - launch_relay_ugv1_agg:
        - tmux new -s launch_relay_ugv1_agg -d
        - tmux send -t launch_relay_ugv1_agg 'source $DEPLOY_WS/devel/basestation/launch/setup.bash' ENTER
        - tmux send -t launch_relay_ugv1_agg 'rosrun topic_tools relay /cm_rel/ugv1/bs/diagnostics_agg /diagnostics_agg' ENTER
        # - launch_relay_ugv2_agg:
        - tmux new -s launch_relay_ugv2_agg -d
        - tmux send -t launch_relay_ugv2_agg 'source $DEPLOY_WS/devel/basestation/launch/setup.bash' ENTER
        - tmux send -t launch_relay_ugv2_agg 'rosrun topic_tools relay /cm_rel/ugv2/bs/diagnostics_agg /diagnostics_agg' ENTER
      
      # stop tmux sessions    
      - stop:
        - rosbag:
          - stop:
            # start stop record
            - tmux new -s launch_rosbag_stop -d
            - tmux send -t launch_rosbag_stop 'source $DEPLOY_WS/devel/basestation/launch/setup.bash' ENTER  
            # stop record node
            - tmux send -t launch_rosbag_stop 'rosnode kill /rosbag_recording_base_station' ENTER
            - sleep 3
          - sessions:
            # stop the sessions
            # - until rostopic list ; do sleep 1; done
            - tmux kill-session -t launch_rosbag_stop
            - tmux kill-session -t launch_rosbag
        - other:
          # remove all the tmux sessions
          - tmux kill-session -t launch_roscore
          - tmux kill-session -t launch_gui
          - tmux kill-session -t ros_shell
          - tmux kill-session -t launch_relay_ugv1_agg
          - tmux kill-session -t launch_relay_ugv2_agg

      - rosclean:
        # stop all ros nodes
        - source $DEPLOY_WS/devel/basestation/launch/setup.bash
        - ps aux | grep ros
        - rosnode kill -a
        - pkill -f ros
        - rosnode list
        - ps aux | grep ros

    ####################################################
    # relaunch rviz in case of crash
    ####################################################
    - relaunch-rviz:
      - 'export DEPLOY_WS=/home/$(whoami)/deploy_ws/'
      - source $DEPLOY_WS/devel/basestation/launch/setup.bash
      - rosrun rviz rviz -d $DEPLOY_WS/src/basestation/basestation_launch/rviz_configs/robot_darpa.rviz

    ####################################################
    # relaunch main gui in case of crash
    ####################################################
    - relaunch-main-gui:
      - 'export DEPLOY_WS=/home/$(whoami)/deploy_ws/'
      - source $DEPLOY_WS/devel/basestation/launch/setup.bash
      - roslaunch $DEPLOY_WS/src/basestation/basestation_gui_python/launch/gui.launch

    ################################################################################################
    # launch node that echos total station data
    ################################################################################################
    - total-station-node:
      - 'export DEPLOY_WS=/home/$(whoami)/deploy_ws/'
      - source $DEPLOY_WS/devel/basestation/repo/setup.bash
      - roslaunch $DEPLOY_WS/src/basestation/total_station_gate_node/launch/total_station_node.launch
